10check_media_minor: check for bad number

diff --git a/prebuilt/etc/init.d/10check_media_minor b/prebuilt/etc/init.d/10check_media_minor
--- a/prebuilt/etc/init.d/10check_media_minor
+++ b/prebuilt/etc/init.d/10check_media_minor
@@ -14,6 +14,12 @@ fi
 # get the minor device number for /dev/store/media
 MM=`/system/xbin/ls -lLn /dev/store/media | sed -e 's/ */	/g' | cut -f7`
 
+if [[ "$MM" < 0 ]];
+then
+	echo "$0: Invalid media minor device number: ${MM}"
+	exit 1
+fi
+
 # get the existing vold.fstab SDCARD= value
 OSTR=`sed -rn -e 's/.*(SDCARD=.*)$/\1/p' /system/etc/vold.fstab`
 
